version: "3"
services:
  #NGNIX & PHP IMAGE
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: laravel-docker/app:latest
    networks:
      - appnet
    volumes:
      - ./web:/var/www/html
    ports:
      - ${APP_PORT}:80
    working_dir: /var/www/html

  #REDIS IMAGE
  cache:
    image: redis:alpine
    networks:
      - appnet
    volumes:
      - cachedata:/data

  # MYSQL IMAGE
  db:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - appnet
    volumes:
      - dbdata:/var/lib/mysql

  # Nodejs IMAGE
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: laravel-docker/node:latest
    networks:
      - appnet
    volumes:
      - ./web:/opt
    working_dir: /opt
    command: Hello, Node js here ;)

  # PHPMyAdmin Image
  myadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PHP_MY_ADMIN_PORT}:80
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local
